name: build&deploy

on:
  push:
    branches:
      - main 

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Build
      run: |
        go build -o app .

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: sa-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Docker Build and Push
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: apijogos
      run: |
        docker build -t apijogos .
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        docker tag apijogos:latest $DOCKER_USERNAME/apijogos:latest
        docker push $DOCKER_USERNAME/apijogos:latest
        docker tag apijogos:latest public.ecr.aws/z1l9l6y3/apijogos:latest
        docker push public.ecr.aws/z1l9l6y3/apijogos:latest
  CD:
    needs: CI
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}  

    - name: Update ECS Service
      run: |
        aws ecs update-service \
          --cluster  ${{ secrets.AWS_ECS_CLUSTER }}\
          --service ${{ secrets.AWS_ECS_SERVICE }} \
          --force-new-deployment
